### ISSUE TITLE
Does not display shortcuts iOS 12 ?

### ISSUE THREAD

**Issue by odahan** [adenearnshaw/AppShortcutsPlugin#17]
// OK it seems the emulator is not able to react to 3D Touch that's certainly why it does not work.
// You can certainly close this issue (or let some message to warn users this does not work on emulator

## Bug Information

Version Number of Plugin:  1.0.0.3
Device Tested On:  
Simulator Tested On:  iPhone 8 iOS 12.0
Version of VS:   latest, up to date
Version of Xamarin:  3.3.0.912540
Versions of other things you are using:  

### Steps to reproduce the Behavior
Launch demo app, show monkey details, Pin, all is right, no error message, no error in the code (tracking executed code in debug mode, no failure)

### Expected Behavior
See something like a shortcut on the iPhone screen

### Actual Behavior
Nothing. Monkey is pinned but not shortcut is displayed

### Screenshots
nothing to see

Additional notes 

Perhaps there is something with iOS 12, I can't test on prior versions.
Long press on Icons does not show anything (just moving icons on the screen), iOS does not react as Android or UWP that's ok. But Where are the shortcuts to be displayed ? 
As there is no screen capture along with your sample code it is hard to tell what to expect visually, what should be seen on screen and how to access shortcuts with iOS...

Of course, thanks for this plugin ! 
And thanks in advance for your answer 
Regards
Olivier

**Comment by adenearnshaw** [comment]
Thank's for the feedback. I've updated the documentation to include a section on testing, which outlines the challenges of testing using the emulator.
