### ISSUE TITLE
[Bug] Menu items not navigating in UWP

### ISSUE THREAD

**Issue by mhrastegary77** [adenearnshaw/AppShortcutsPlugin#26]
## Description
 Menu items not working in UWP! 

## Bug Information
Version Number of Plugin:  1.0.0.3
Device Tested On:  PC
Version of VS:   16.5.4
Version of Xamarin:  4.6

### Steps to reproduce the Behavior
1. Create some AppShortCuts in App.Xaml.CS
2. RightClick on the App Tile 
3. Click one of the short cuts
and all of them navigates the app to the main page

**Comment by adenearnshaw** [comment]
UWP requires additional setup in the Platform's App.xaml.cs. If this isn't implemented the navigation isn't invoked correctly.
Here's a sample: https://github.com/adenearnshaw/AppShortcutsPluginSamples/tree/master/UWP
