### ISSUE TITLE
Multiple navigation stacks

### ISSUE THREAD

**Issue by KerosenoDev** [adenearnshaw/AppShortcutsPlugin#28]
At least on Android, every time a shortcut is pressed, with the application in memory, the constructor is initialized again with a new navigation stack. Then the shortcut page opens, but if I go back, it goes back to the previous navigation stack.

Is there a way to remove the old navigation stack? Or add the shortcut page to the existing stack?

Thanks and regards.

**Comment by KerosenoDev** [comment]
It hasn't happened in iOS, it doesn't go back through the constructor if the application is in memory. Don't create more navigations stacks.

**Comment by KerosenoDev** [comment]
This has saved me: [https://stackoverflow.com/questions/44826664/xamarin-android-app-resumed-by-shortcut-intent-master-and-detail-must-be-set-b](https://stackoverflow.com/questions/44826664/xamarin-android-app-resumed-by-shortcut-intent-master-and-detail-must-be-set-b)

In MainActivity, I had to add `LaunchMode = LaunchMode.SingleTask`.

**Comment by adenearnshaw** [comment]
Thanks for the update. I was going to explore it this evening
